# Generated by Django 5.0.1 on 2025-03-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='address',
            new_name='village_or_town',
        ),
    ]
