# Generated by Django 5.0.1 on 2025-04-01 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_address_user_address_village_or_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
