# Generated by Django 5.0.1 on 2025-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
