# Generated by Django 5.0.1 on 2025-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
