# Generated by Django 5.0.1 on 2025-04-07 06:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='Email', to=settings.AUTH_USER_MODEL),
        ),
    ]
