# Generated by Django 5.0.1 on 2025-04-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_address_email_alter_user_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
