# Generated by Django 5.0.1 on 2025-04-07 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='email',
        ),
        migrations.AlterField(
            model_name='user_address',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
