# Generated by Django 5.0.1 on 2025-03-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='payment_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_signature',
        ),
    ]
