# Generated by Django 5.0.1 on 2025-03-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
